//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.SubItems = new HashSet<Item>();
        }
    
        public int Id { get; set; }
        public string Extension { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public string Size { get; set; }
        public string Time { get; set; }
        public int Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> SubItems { get; set; }
        public virtual Item ParentItems { get; set; }
        public virtual User User { get; set; }
    }
}
